language: python
python:
  - "3.4"

env:
  global:
    - TRAVIS_TAG="$(date -u '+%Z-%y%m%d-%H%M')"

branches:
  only:
    - "1.0"

script:
  - python check.py

before_deploy:
  - mkdir SChinese
  - mv * SChinese/ || true
  - cd SChinese/ && mv check.py ../ && mv output.log ../ && cd ../
  - curl -sSL -o packer.zip https://github.com/sffxzzp/Starbound-Chinese/releases/download/packer/asset_packer.zip && unzip packer.zip
  - chmod a+x asset_packer && ./asset_packer "SChinese" "SChinese.pak"
  - zip -9 "SChinese.zip" "SChinese.pak"
  - export RBody=$(cat ./output.log)
  - git config --local user.name "$user_name"
  - git config --local user.email "$user_email"
  - git tag "$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: $gh_token
  prerelease: true
  draft: false
  title: $TRAVIS_TAG
  body: $RBody
  file: "SChinese.zip"
  skip_cleanup: true
  on:
    branch: "1.0"